print("considera il seguente circuito:")
print("+--R1----+--+")
print("|        |  |")
print("--       R  R")
print("-        2  3")
print("|        |  |")
print("+--------+--+")
R1 = float(input("Inserisci Il valore di R1:\n"))
R2 = float(input("Inserisci Il valore di R2:\n"))
R3 = float(input("Inserisci Il valore di R3:\n"))
print("La resistenza totale è:")
Rpara = 1/((1/R2)+(1/R3))
Rtot = R1 + Rpara
print(Rtot)